name: app_deploy_screenshots
description: 'Generates App Deployment Screenshots'
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: '>=3.35.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.16.0 
dev_dependencies:
  flutter_lints: ^6.0.0 
  test_api: ^0.7.6 

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
